### PR TITLE
Update noarch flag

### LINKED ISSUE #7: UserWarning about pre-link script
When updating my packages, I noticed the following warning:

> UserWarning: Package conda-forge::pyvisa-py-0.2-py_1000 uses a pre-link script. Pre-link scripts are potentially dangerous.
This is because pre-link scripts have the ability to change the package contents in the
package cache, and therefore modify the underlying files for already-created conda
environments.  Future versions of conda may deprecate and ignore pre-link scripts.

This is on Windows using conda 4.5.11 and pyvisa-py-0.2-py_1000. I'm not sure if more info than that is relevant.

Honestly I don't know if this is a spurious/false-positive warning, if the pre-link script can be avoided, or where it even is located (as I could not find anything related in the recipe folder).

### PR DESCRIPTION
**Pull request by bilderbuchi**
Hopefully, this resolves #7 and @jamienoss difficulties.

@conda-forge-admin, please rerender.

### CODE REVIEW

**Comment by jamienoss** [comment]
@bilderbuchi Thanks for this.

I just wanted to double-check though, are all of these changes intended rather than just those to recipe/meta.yaml?

**Comment by bilderbuchi** [comment]
You will notice that conda-forge-linter added a commit with most of those changes when called to rerender as per PR instructions.

**Comment by jamienoss** [comment]
>You will notice that conda-forge-linter added a commit with most of those changes when called to rerender as per PR instructions.

Ok cool, I hadn't noticed, thank you for pointing this out.

**Comment by bilderbuchi** [comment]
Sure. Do you have a way to test if this PR solves your problem?

**Comment by jamienoss** [comment]
I'll try now...

**Comment by jamienoss** [comment]
It seems to, but let me just build from the old recipe and double-check that that fails.

**Comment by jamienoss** [comment]
Sorry, distractions and build errors - had to downgrade conda to 4.6 in order to get the old recipe to build. This then reproduced #7. I wanted to make sure that no local build/install issues masked anything.

This PR has solved my issue stated in #7.

**Comment by bilderbuchi** [comment]
Great!  @mariusvniekerk, could you review and merge, please?

**Comment by bilderbuchi** [comment]
Thanks! :+1:

**Comment by jamienoss** [comment]
Thanks to all.

**Pull request merged**
