### PR TITLE
Update 4.1.5

### PR DESCRIPTION
**Pull request by mtsolmn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Update for new release of PyVISA-py 4.1.5
Also updated the dependencies based off of setup.cfg

@conda-forge/core
pinging the admins because it seems the maintainers are inactive

### CODE REVIEW

**Comment by mtsolmn** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
hey @mtsolm thanks for picking this up! Looks really good.

Usually we give the maintainers a bit of time to merge before we as the core team step in.

Let me know when you're done with changes!

**Comment by greyltc** [comment]
Hmm. I would have expected the module to be named `pyvisa_py` and the tests run on that, but that didn't seem to work

**Comment by greyltc** [comment]
This module looks to me like it's being installed with the wrong name.  
Python modules should not have `-` in their names.  
For `import pyvisa-py`, `pyvisa-py` gets interpreted as `pyvisa` minus `py`

[upstream](https://github.com/pyvisa/pyvisa-py) names the module without breaking any rules, so this is a conda-forge/pip issue.

Let's merge this version bump now and I'll do a seperate PR to try to fix the module naming issue

**Review by greyltc — APPROVED** [review]
Thanks for the fixes/updates @mtsolmn

**Comment by greyltc** [comment]
@conda-forge-admin, please rerender

**Comment by mtsolmn** [comment]
@greyltc I believe everything is working as it should (albeit the naming convention is a bit confusing). There are two different but complementary projects: PyVISA and PyVISA-py. PyVISA is a wrapper/interface library for using the VISA standard in python. However, the VISA standard libraries are proprietary National Instruments libraries (see NI-VISA) and are not freely available (although the standard itself is). Since not everyone has access to the VISA libraries, an open-source equivalent for use with python was created -- PyVISA-py. Essentially, it is a backend for PyVISA for users without direct access to the proprietary libraries. As such, PyVISA-py isn't called directly in any code, it is set as the backend.

In fact, a better test to check successful install is to run:
`python -c "import visa; rm = visa.ResourceManager('@py')"`

This sets the backend to use PyVISA-py and will fail if the backend isn't found. You can see this info about your system and what backends are available by running:
`python -m visa info`

PyVISA-py was created after the original PyVISA project to fill this need. VISA would probably be a better name for the module, however, that is taken as the API for the payment processor. Not sure what the name should ideally by, but at any rate, this is the name all the users now know so I think this is the naming scheme to stick with.

**Comment by greyltc** [comment]
Hi @mtsolmn 

[PEP8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) tells us how modules should be named

Upstream has a folder name [pyvisa_py](https://github.com/pyvisa/pyvisa-py/tree/master/pyvisa_py) for the module in their repo

When I run `conda install -c conda-forge pyvisa-py`, a folder named `pyvisa-py` appears in my anaconda site-packages folder. I guess that's a violation of what we can read in PEP8?

Here's the code in pyvisa that helps ResourceManager find a backend: https://github.com/pyvisa/pyvisa/blob/master/pyvisa/highlevel.py#L2823-L2828
It first looks for a module named `pyvisa_py` and then falls back to looking one named `pyvisa-py`

After a bit more digging, I'm starting to think this module name thing might be a bug for upstream...I'm still convinced it's wrong in conda-forge as it stands now though, but I'm not sure who's fault it is.

As for testing, upstream has a [specific testsuite for the pyvisa_py module](https://github.com/pyvisa/pyvisa-py/tree/master/pyvisa_py/testsuite) that is of course not pyvisa's tests, which is why I thought we should try to run those.

I agree that `python -c "import visa; rm = visa.ResourceManager('@py')"` needs to be a test here.

**Comment by mtsolmn** [comment]
Hi @greyltc 

Thanks for the clarification. After reading (and seeing your https://github.com/pyvisa/pyvisa-py/issues/253) I understand what you are referring to. I myself am not sure what the answer is but thanks for reporting the issue on pyvisa-py.

**Pull request merged**
